version: '3.8'

services:
  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"    # API
      - "9001:9001"    # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Client (optional - for management)
  mc:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    environment:
      MC_HOST_local: http://minioadmin:minioadmin@minio:9000
    volumes:
      - ./scripts:/scripts
    command: sh -c "sleep 10 && mc alias set local http://minio:9000 minioadmin minioadmin && mc mb local/videos local/images local/documents local/courses local/lessons && mc policy set public local/videos && mc policy set public local/images && mc policy set public local/documents && mc policy set public local/courses && mc policy set public local/lessons && echo 'MinIO buckets created successfully' && tail -f /dev/null"
    restart: unless-stopped

volumes:
  minio_data:
    driver: local

networks:
  default:
    name: minio-network
